// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQWsVM-OxVtyT2WeZIZFcPEsoxhnOKD74',
    appId: '1:509171996091:web:099cb604bdd7925072a09e',
    messagingSenderId: '509171996091',
    projectId: 'ksfood-a112c',
    authDomain: 'ksfood-a112c.firebaseapp.com',
    databaseURL: 'https://ksfood-a112c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ksfood-a112c.appspot.com',
    measurementId: 'G-K9S5LPYVCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUAcPGosRrB28qd3zKq60EUGcOJMEOdI',
    appId: '1:509171996091:android:e6f8c2e36c3bb2c072a09e',
    messagingSenderId: '509171996091',
    projectId: 'ksfood-a112c',
    databaseURL: 'https://ksfood-a112c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ksfood-a112c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX2HiOnWTKzU5XNf1nIJHmjx-HnsdYNWQ',
    appId: '1:509171996091:ios:f4c37b837616430a72a09e',
    messagingSenderId: '509171996091',
    projectId: 'ksfood-a112c',
    databaseURL: 'https://ksfood-a112c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ksfood-a112c.appspot.com',
    androidClientId: '509171996091-ees649522skmetbq27hddc4j7emh9ku2.apps.googleusercontent.com',
    iosClientId: '509171996091-i5mt4cerrq1vmqjpa81aikcdlgjqg7pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ksfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX2HiOnWTKzU5XNf1nIJHmjx-HnsdYNWQ',
    appId: '1:509171996091:ios:45b4ae3e8d5da31472a09e',
    messagingSenderId: '509171996091',
    projectId: 'ksfood-a112c',
    databaseURL: 'https://ksfood-a112c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ksfood-a112c.appspot.com',
    androidClientId: '509171996091-ees649522skmetbq27hddc4j7emh9ku2.apps.googleusercontent.com',
    iosClientId: '509171996091-6auq6a2948k9p0qg26lof6cu8a189m0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ksfood.RunnerTests',
  );
}
